[project]
name = "or-models"
version = "0.1.0"
description = "Playground for OR models and bleeding edge modeling tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pyoframe[highs]>=0.2.0",
]
